import {
  addFooter,
  addHeader,
  addInfoGrid,
  addSectionTitle,
  addSignatureBlock,
  createPdf,
  downloadPdf,
  formatDate,
  money,
  type PdfSettings,
} from "@/lib/pdf/pdfEngine";

export function generateCertificatePdf(
  certificate: any,
  settings?: PdfSettings
) {
  const doc = createPdf("Investment Certificate", settings);

  const clubName = settings?.clubName || "LP45 Private Investment Club";
  const certificateNumber = certificate.certificate_number || "N/A";

  const grossROI = Number(
    certificate.gross_roi_amount ?? certificate.expected_roi_amount ?? 0
  );

  const deductionApplicable = Boolean(certificate.deduction_applicable);
  const deductionLabel = certificate.deduction_label || "WHT";
  const deductionRate = Number(certificate.deduction_rate || 0);
  const deductionAmount = Number(certificate.deduction_amount || 0);

  const netROI = Number(
    certificate.net_roi_amount ?? certificate.expected_roi_amount ?? 0
  );

  const netTotalReturn = Number(
    certificate.net_total_return ?? certificate.expected_total_return ?? 0
  );

  addHeader(
    doc,
    "Investment Certificate",
    `Certificate No: ${certificateNumber}`,
    settings
  );

  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(1.2);
  doc.rect(12, 58, 186, 205);

  doc.setTextColor(226, 232, 240);
  doc.setFontSize(42);
  doc.setFont("helvetica", "bold");
  doc.text("LP45", 72, 150, { angle: -25 });

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("THIS CERTIFIES THAT", 82, 72);

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(certificate.members?.full_name || "Member", 105, 88, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(
    `Membership Number: ${
      certificate.members?.membership_number ||
      certificate.membership_number ||
      "N/A"
    }`,
    105,
    98,
    { align: "center" }
  );

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);

  const certificateText = doc.splitTextToSize(
    `has participated in the investment opportunity stated below under ${clubName}, subject to the terms, deduction structure, maturity timeline, and return arrangement approved for this investment.`,
    160
  );

  doc.text(certificateText, 25, 112);

  let y = 132;

  y = addSectionTitle(doc, "Investment Details", y);

  y = addInfoGrid(
    doc,
    [
      {
        label: "Investment Title",
        value: certificate.investment_opportunities?.title || "N/A",
      },
      {
        label: "Investment Type",
        value:
          certificate.investment_opportunities?.investment_type ||
          "General Investment",
      },
      {
        label: "Capital Invested",
        value: money(certificate.amount_invested),
      },
      {
        label: "Investment Date",
        value: formatDate(certificate.invested_at),
      },
      {
        label: "Maturity Date",
        value: formatDate(certificate.investment_opportunities?.maturity_date),
      },
      {
        label: "Status",
        value: certificate.status || "Active",
      },
    ],
    y
  );

  y = addSectionTitle(doc, "Return Summary", y + 2);

  y = addInfoGrid(
    doc,
    [
      {
        label: "ROI Rate",
        value: `${certificate.expected_roi_percent}%`,
      },
      {
        label: "Gross ROI",
        value: money(grossROI),
      },
      {
        label: "Deduction / Tax",
        value: deductionApplicable
          ? `${deductionLabel} @ ${deductionRate}%`
          : "Not applicable",
      },
      {
        label: "Deduction Amount",
        value: money(deductionAmount),
      },
      {
        label: "Net ROI",
        value: money(netROI),
      },
      {
        label: "Net Total Return",
        value: money(netTotalReturn),
      },
    ],
    y
  );

  y = addSectionTitle(doc, "Certificate Authenticity", y + 2);

  y = addInfoGrid(
    doc,
    [
      {
        label: "Certificate Number",
        value: certificateNumber,
      },
      {
        label: "Issued Date",
        value: formatDate(certificate.invested_at),
      },
      {
        label: "Generated By",
        value: "LP45 System",
      },
      {
        label: "Verification",
        value: "Portal verification placeholder",
      },
    ],
    y
  );

  doc.setFillColor(255, 251, 235);
  doc.rect(20, y + 2, 170, 22, "F");

  doc.setTextColor(146, 64, 14);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("DEDUCTION / TAX DISCLOSURE", 25, y + 9);

  doc.setFont("helvetica", "normal");
  const disclosure = doc.splitTextToSize(
    "Where deduction is applicable, the Net ROI stated on this certificate represents the amount due to the member after deduction from Gross ROI. The deduction may represent WHT, VAT, or any other approved charge configured for the investment opportunity.",
    160
  );
  doc.text(disclosure, 25, y + 15);

  addSignatureBlock(
    doc,
    250,
    settings?.investmentManagerName || "Investment Manager",
    settings?.clubSecretaryName || "Club Secretary"
  );

  addFooter(doc, settings?.certificateFooterNote, settings);

  downloadPdf(doc, `investment-certificate-${certificateNumber}`);
}