import {
  addFooter,
  addHeader,
  addInfoGrid,
  addSectionTitle,
  createPdf,
  downloadPdf,
  formatDate,
  money,
  type PdfSettings,
} from "@/lib/pdf/pdfEngine";

type DepositReceiptPayload = {
  deposit: any;
  settings?: PdfSettings;
};

export function generateDepositReceiptPdf({
  deposit,
  settings,
}: DepositReceiptPayload) {
  const doc = createPdf("Deposit Receipt", settings);

  const receiptNumber =
    deposit.receipt_number ||
    deposit.payment_reference ||
    `DEP-${String(deposit.id || "").slice(0, 8).toUpperCase()}`;

  addHeader(
    doc,
    "Deposit Receipt",
    `Receipt / Reference No: ${receiptNumber}`,
    settings
  );

  let y = 60;

  y = addSectionTitle(doc, "Member Information", y);

  y = addInfoGrid(
    doc,
    [
      {
        label: "Member Name",
        value: deposit.members?.full_name || "N/A",
      },
      {
        label: "Membership Number",
        value: deposit.members?.membership_number || "N/A",
      },
      {
        label: "Email",
        value: deposit.members?.email || "N/A",
      },
      {
        label: "Phone",
        value: deposit.members?.phone || "N/A",
      },
    ],
    y
  );

  y = addSectionTitle(doc, "Deposit Details", y + 2);

  y = addInfoGrid(
    doc,
    [
      {
        label: "Amount Deposited",
        value: money(deposit.amount),
      },
      {
        label: "Payment Reference",
        value: deposit.payment_reference || "N/A",
      },
      {
        label: "Deposit Status",
        value: deposit.status || "N/A",
      },
      {
        label: "Submitted Date",
        value: formatDate(deposit.created_at),
      },
      {
        label: "Approved Date",
        value: formatDate(deposit.approved_at),
      },
      {
        label: "Receipt Upload",
        value: deposit.receipt_url ? "Receipt uploaded" : "No receipt uploaded",
      },
    ],
    y
  );

  y = addSectionTitle(doc, "Receipt Confirmation", y + 2);

  doc.setFillColor(240, 253, 244);
  doc.rect(15, y, 180, 38, "F");

  doc.setTextColor(22, 101, 52);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Deposit Confirmation", 20, y + 10);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  const confirmationText = doc.splitTextToSize(
    `The deposit of ${money(
      deposit.amount
    )} has been credited to the member wallet 
and reflected in the member ledger.`,
    155
  );

  doc.text(confirmationText, 20, y + 18);

  y += 52;

  y = addSectionTitle(doc, "System Details", y);

  y = addInfoGrid(
    doc,
    [
      {
        label: "Generated By",
        value: "LP45 System",
      },
      {
        label: "Generated Date",
        value: new Date().toLocaleDateString(),
      },
      {
        label: "Document Type",
        value: "Deposit Receipt",
      },
      {
        label: "Verification",
        value: "Electronically generated.",
      },
    ],
    y
  );

  addFooter(
    doc,
    "This deposit receipt is system-generated from LP45 Private Investment Club records.",
    settings
  );

  downloadPdf(doc, `deposit-receipt-${receiptNumber}`);
}