import {
  addFooter,
  addHeader,
  addInfoGrid,
  addSectionTitle,
  createPdf,
  downloadPdf,
  formatDate,
  money,
  type PdfSettings,
} from "@/lib/pdf/pdfEngine";

type RoiAdvicePayload = {
  roiRecord: any;
  settings?: PdfSettings;
};

export function generateRoiAdvicePdf({
  roiRecord,
  settings,
}: RoiAdvicePayload) {
  const doc = createPdf("ROI Payment Advice", settings);

  const adviceNumber =
    roiRecord.advice_number ||
    roiRecord.reference ||
    `ROI-${String(roiRecord.id || "").slice(0, 8).toUpperCase()}`;

  const grossROI = Number(roiRecord.gross_roi_amount ?? roiRecord.roi_amount ?? 0);
  const deductionApplicable = Boolean(roiRecord.deduction_applicable);
  const deductionLabel = roiRecord.deduction_label || "WHT";
  const deductionRate = Number(roiRecord.deduction_rate || 0);
  const deductionAmount = Number(roiRecord.deduction_amount || 0);
  const netROI = Number(roiRecord.net_roi_amount ?? roiRecord.roi_amount ?? 0);
  const netTotalPayable = Number(
    roiRecord.net_total_payable ?? roiRecord.total_payable ?? 0
  );

  addHeader(
    doc,
    "ROI Payment Advice",
    `Advice / Reference No: ${adviceNumber}`,
    settings
  );

  let y = 60;

  y = addSectionTitle(doc, "Member Information", y);

  y = addInfoGrid(
    doc,
    [
      { label: "Member Name", value: roiRecord.members?.full_name || "N/A" },
      {
        label: "Membership Number",
        value: roiRecord.members?.membership_number || "N/A",
      },
      { label: "Email", value: roiRecord.members?.email || "N/A" },
      { label: "Phone", value: roiRecord.members?.phone || "N/A" },
    ],
    y
  );

  y = addSectionTitle(doc, "Investment Information", y + 2);

  y = addInfoGrid(
    doc,
    [
      {
        label: "Investment",
        value: roiRecord.investment_opportunities?.title || "N/A",
      },
      {
        label: "Investment Type",
        value:
          roiRecord.investment_opportunities?.investment_type ||
          "General Investment",
      },
      { label: "Capital Amount", value: money(roiRecord.capital_amount) },
      { label: "ROI Rate", value: `${Number(roiRecord.roi_percent || 0)}%` },
      { label: "Maturity Date", value: formatDate(roiRecord.maturity_date) },
      { label: "Status", value: roiRecord.status || "N/A" },
    ],
    y
  );

  y = addSectionTitle(doc, "ROI Payment Breakdown", y + 2);

  y = addInfoGrid(
    doc,
    [
      { label: "Gross ROI", value: money(grossROI) },
      {
        label: "Deduction / Tax",
        value: deductionApplicable
          ? `${deductionLabel} @ ${deductionRate}%`
          : "Not applicable",
      },
      { label: "Deduction Amount", value: money(deductionAmount) },
      { label: "Net ROI Credited", value: money(netROI) },
      { label: "Net Total Payable", value: money(netTotalPayable) },
      { label: "Credited Date", value: formatDate(roiRecord.credited_at) },
    ],
    y
  );

  y = addSectionTitle(doc, "Payment Confirmation", y + 2);

  doc.setFillColor(240, 253, 244);
  doc.rect(15, y, 180, 38, "F");

  doc.setTextColor(22, 101, 52);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("ROI Credit Confirmation", 20, y + 10);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  const confirmationText = doc.splitTextToSize(
    `This confirms that the net ROI of ${money(
      netROI
    )} has been recorded on the LP45 Private Investment Club platform. Where status is credited or paid, the amount has been credited to the member wallet and reflected in the member ledger.`,
    155
  );

  doc.text(confirmationText, 20, y + 18);

  y += 52;

  y = addSectionTitle(doc, "System Details", y);

  y = addInfoGrid(
    doc,
    [
      { label: "Generated By", value: "LP45 System" },
      { label: "Generated Date", value: new Date().toLocaleDateString() },
      { label: "Document Type", value: "ROI Payment Advice" },
      { label: "Verification", value: "Electronically generated." },
    ],
    y
  );

  addFooter(
    doc,
    "This ROI payment advice is system-generated from LP45 Private Investment Club records.",
    settings
  );

  downloadPdf(doc, `roi-advice-${adviceNumber}`);
}