import {
  addFooter,
  addHeader,
  addInfoGrid,
  addSectionTitle,
  createPdf,
  downloadPdf,
  formatDate,
  money,
  type PdfSettings,
} from "@/lib/pdf/pdfEngine";

type WithdrawalAdvicePayload = {
  withdrawal: any;
  settings?: PdfSettings;
};

export function generateWithdrawalAdvicePdf({
  withdrawal,
  settings,
}: WithdrawalAdvicePayload) {
  const doc = createPdf("Withdrawal Advice", settings);

  const adviceNumber =
    withdrawal.advice_number ||
    withdrawal.reference ||
    `WDL-${String(withdrawal.id || "").slice(0, 8).toUpperCase()}`;

  addHeader(
    doc,
    "Withdrawal Advice",
    `Advice / Reference No: ${adviceNumber}`,
    settings
  );

  let y = 60;

  y = addSectionTitle(doc, "Member Information", y);

  y = addInfoGrid(
    doc,
    [
      { label: "Member Name", value: withdrawal.members?.full_name || "N/A" },
      {
        label: "Membership Number",
        value: withdrawal.members?.membership_number || "N/A",
      },
      { label: "Email", value: withdrawal.members?.email || "N/A" },
      { label: "Phone", value: withdrawal.members?.phone || "N/A" },
    ],
    y
  );

  y = addSectionTitle(doc, "Withdrawal Details", y + 2);

  y = addInfoGrid(
    doc,
    [
      { label: "Amount Requested", value: money(withdrawal.amount) },
      { label: "Withdrawal Status", value: withdrawal.status || "N/A" },
      { label: "Requested Date", value: formatDate(withdrawal.created_at) },
      { label: "Approved Date", value: formatDate(withdrawal.approved_at) },
      { label: "Paid Date", value: formatDate(withdrawal.paid_at) },
      {
        label: "Payment Account",
        value:
          withdrawal.bank_account_number ||
          withdrawal.account_number ||
          "Not specified",
      },
    ],
    y
  );

  y = addSectionTitle(doc, "Payment Confirmation", y + 2);

  doc.setFillColor(240, 253, 244);
  doc.rect(15, y, 180, 38, "F");

  doc.setTextColor(22, 101, 52);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Withdrawal Payment Advice", 20, y + 10);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  const confirmationText = doc.splitTextToSize(
    `This confirms that a withdrawal request of ${money(
      withdrawal.amount
    )} has been recorded on the LP45 platform. Where status is paid, the amount has been processed and reflected in the member ledger.`,
    155
  );

  doc.text(confirmationText, 20, y + 18);

  y += 52;

  y = addSectionTitle(doc, "System Details", y);

  y = addInfoGrid(
    doc,
    [
      { label: "Generated By", value: "LP45 System" },
      { label: "Generated Date", value: new Date().toLocaleDateString() },
      { label: "Document Type", value: "Withdrawal Advice" },
      { label: "Verification", value: "Electronically generated." },
    ],
    y
  );

  addFooter(
    doc,
    "This withdrawal advice is system-generated from LP45 Private Investment Club records.",
    settings
  );

  downloadPdf(doc, `withdrawal-advice-${adviceNumber}`);
}